hw4: WordNetwork.o HashTable.o Queue.o Node.o main.o
	g++ WordNetwork.o HashTable.o Queue.o Node.o main.o -o hw4

WordNetwork.o: WordNetwork.cpp
	g++ -c WordNetwork.cpp

HashTable.o: HashTable.cpp
	g++ -c HashTable.cpp

Queue.o: Queue.cpp
	g++ -c Queue.cpp

Node.o: Node.cpp
	g++ -c Node.cpp

main.o: main.cpp
	g++ -c main.cpp