hw2: BinarySearchTree.o BinaryNode.o main.o
	g++ BinarySearchTree.o BinaryNode.o main.o -o hw2

BinarySearchTree.o: BinarySearchTree.cpp
	g++ -c BinarySearchTree.cpp

BinaryNode.o: BinaryNode.cpp
	g++ -c BinaryNode.cpp

main.o: main.cpp
	g++ -c main.cpp