simulator: Heap.o Request.o simulator.o main.o
	g++ Heap.o Request.o simulator.o main.o -o simulator

Heap.o: Heap.cpp
	g++ -c Heap.cpp

Request.o: Request.cpp
	g++ -c Request.cpp

simulator.o: simulator.cpp
	g++ -c simulator.cpp

main.o: main.cpp
	g++ -c main.cpp